version: 3

includes:
  task_win:
    taskfile: ./Taskfile_windows.yml
    optional: true

vars:
  GIT_VERSION:
    sh: git describe --tags --always
  GIT_REV:
    sh: git rev-parse --short HEAD
  APP_NAME: StrongDMM
  BIN_DST: '{{.APP_NAME}}{{exeExt}}'
  BUILD_VARS: -X sdmm/env.Version={{.GIT_VERSION}} -X sdmm/env.Revision={{.GIT_REV}}
  LD_FLAGS_WINDOWS:
    sh: echo '{{if eq OS "windows"}}-H windowsgui -extldflags=-static{{end}}'
  LD_FLAGS: -s -w {{.BUILD_VARS}} {{.LD_FLAGS_WINDOWS}}
  BUILD_ARGS: -trimpath -ldflags="{{.LD_FLAGS}}"

tasks:
  clean-sdmm:
    cmds:
      - rm -frd ./dst

  clean-sdmmparser:
    dir: third_party/sdmmparser/src
    cmds:
      - cargo clean

  clean:
    deps:
      - clean-sdmmparser
      - clean-sdmm

  run:
    deps:
      - build-sdmmparser
    cmds:
      - go run {{.BUILD_ARGS}} .

  build:
    deps:
      - build-sdmmparser
    cmds:
      - go build {{.BUILD_ARGS}} -o "dst/{{.BIN_DST}}" .

  build-sdmmparser:
    dir: third_party/sdmmparser/src
    cmds:
      - cargo build --release

  release-files-unzip:
    dir: dst
    cmds:
      - mkdir -p bin archive
      - cp Windows/StrongDMM.exe bin/strongdmm-{{.GIT_VERSION}}-x86_64-pc-windows-gnu.exe
      - cp Linux/StrongDMM bin/strongdmm-{{.GIT_VERSION}}-x86_64-unknown-linux-gnu
      - cp macOS/StrongDMM bin/strongdmm-{{.GIT_VERSION}}-x86_64-apple-darwin
      - zip -rj archive/strongdmm-windows.zip Windows
      - zip -rj archive/strongdmm-linux.zip Linux
      - zip -rj archive/strongdmm-macos.zip macOS

  release-files-hash:
    dir: dst/bin
    cmds:
      - sha256sum ./strongdmm-{{.GIT_VERSION}}-x86_64-pc-windows-gnu.exe | tee -a "strongdmm-{{.GIT_VERSION}}-x86_64-pc-windows-gnu.exe.sha256"
      - sha256sum ./strongdmm-{{.GIT_VERSION}}-x86_64-unknown-linux-gnu | tee -a "strongdmm-{{.GIT_VERSION}}-x86_64-unknown-linux-gnu.sha256"
      - sha256sum ./strongdmm-{{.GIT_VERSION}}-x86_64-apple-darwin | tee -a "strongdmm-{{.GIT_VERSION}}-x86_64-apple-darwin.sha256"

  release-files:
    cmds:
      - task: release-files-unzip
      - task: release-files-hash
