name: Bug Report
description: Create a report to help reproduce and fix the issue
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of StrongDMM did you use?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: how-did-it-happen
    attributes:
      label: Reproduction
      description: How did you manage to make the error happen?
      placeholder: How did you do it?
      value: "1. Run StrongDMM"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. The logs can be found with `Help -> Open Logs Folder`. This will be automatically formatted into code, so no need for backticks.
      render: shell
