name: Feature Request
description: Suggest an idea for this project
title: "Feature Request: "
labels: ["enhancement"]
body:
  - type: markdown
    id: feature-request
    attributes:
      label: Feature Request
      description: What new feature do you want to request?
    validations:
      required: true
