package strongdmm.event

enum class Event {
    GLOBAL_RESET_ENVIRONMENT, GLOBAL_SWITCH_MAP, GLOBAL_SWITCH_ENVIRONMENT, GLOBAL_UPD_MAP_MOUSE_POS,
    ENVIRONMENT_OPEN, ENVIRONMENT_FETCH,
    MAP_OPEN,
    FRAME_COMPOSE
}
