package strongdmm.event

enum class Event {
    GLOBAL_RESET_ENVIRONMENT, GLOBAL_SWITCH_MAP, GLOBAL_SWITCH_ENVIRONMENT, GLOBAL_UPD_MAP_MOUSE_POS,
    GLOBAL_CLOSE_MAP,

    ENVIRONMENT_OPEN, ENVIRONMENT_FETCH,
    MAP_OPEN, MAP_CLOSE, MAP_FETCH_SELECTED, MAP_FETCH_OPENED, MAP_SWITCH, MAP_FETCH_AVAILABLE,
    FRAME_COMPOSE,
    AVAILABLE_MAPS_OPEN
}
