package strongdmm.event

enum class Event {
    GLOBAL_RESET_ENVIRONMENT, GLOBAL_SWITCH_MAP, GLOBAL_SWITCH_ENVIRONMENT,
    ENVIRONMENT_OPEN, ENVIRONMENT_FETCH,
    MAP_OPEN,
    FRAME_COMPOSE,
    CANVAS_VIEW_TRANSLATE, CANVAS_VIEW_SCALE
}
